### ISSUE TITLE
Where can i get pretrain arcface?

### ISSUE THREAD

**Issue by dungx48** [zhouyuchong/face-recognition-deepstream#10]
I clicked to model zoo in insightface and i don't know which one to choose? 
Thank everybody for reading :+1:

**Comment by zhouyuchong** [comment]
you can choose any one of them, as you like.

**Comment by dungx48** [comment]
> you can choose any one of them, as you like.

i'm newbie and i want to follow your pipeline so it can be to word

**Comment by zhouyuchong** [comment]
@dungx48 for example, arcface with [MobileFaceNet](https://drive.google.com/file/d/1RHyJIeYuHduVDDBTn3ffpYEZoXWRamWI/view), download then follow the [tensorrtx](https://github.com/wang-xinyu/tensorrtx/tree/master/arcface) to get a `*.engine` file. 

if there is some problem during generating the engine, maybe it is because the **version** in **tensorrtx** is quite low. I've changed some codes to fit trt in ds 6.1. you can find them [here](https://github.com/zhouyuchong/tensorrtx).

**Comment by dungx48** [comment]
What mxnet version are you using?
I think i have problem in mxnet library? Each mxnet version i used, there is some problem

**Comment by dungx48** [comment]
My problem in '''python gen_wts.py''', i think it dont related to tensorrtx.

**Comment by zhouyuchong** [comment]
> What mxnet version are you using? I think i have problem in mxnet library? Each mxnet version i used, there is some problem

I'm using [mxnet-cu112](https://pypi.org/project/mxnet-cu112/) which correspond to cuda 11.2. However, it works fine so far with ds 6.1 which contains cuda 11.6.
