### ISSUE TITLE
Anonymous face

### ISSUE THREAD

**Issue by sbmalik** [zhouyuchong/face-recognition-deepstream#2]
No matter which video, I run it always gives print
`THIS AN ANONYMOUS FACE, DISCARD`
is there a way to solve it?

**Comment by sbmalik** [comment]
@zhouyuchong `obj_meta.parent` always give none... Can you please guide me how to tackle this ?

**Comment by zhouyuchong** [comment]
@[sbmalik](https://github.com/sbmalik) sorry, this repo has many problems, but I'm been busy with another job and didn't fix them. For your problem, that's because `nvvideoconvert` will drop the `obj.parent` from the metadata, so you should do the job earlier by adding the *probe* you want to extract the `obj.parent` before the `nvvideoconv`.

I'll find some time to update this repo recently and @ you at that time.

**Comment by sbmalik** [comment]
@zhouyuchong Thank you for your response, I'll try your solution.
 
 However, Looking forward for the updation of this repository.

**Comment by zhouyuchong** [comment]
@sbmalik Hi, I update this repo. you can check the codes now. `main` branch can play all format video files, and the `process-mode-2-version` could only play rtsp source on my pc.

the old version is using retinaface as secondary `nvinfer` and set its `process-mode` to 2, which means only detect face on the top of yolo's detections. However, for some reason, it fails on regular local video files, there is no error and no debug information which make it hard for me to find the reason.

So I have to give up on Plan A and try to connect face and body manually. The performance is not very good to be honest especially when crowded.

I'll dig into this if I have time.

**Comment by sbmalik** [comment]
@zhouyuchong I check it and it's working very well. Thank you for providing the support on this repo. Moreover, I wanted to ask that I am unable to get the face-recognition (detection is working like charm). Can you share any sample video where recognition is working good? 

if you want I can open another issue because the problem related to this is solved already.

**Comment by zhouyuchong** [comment]
@sbmalik what do you mean `unable to get the face-recognition`? I've tested different video types:rtsp, mp4, h264, etc. Just find one on the Internet, if there is something wrong, please let me know.

**Comment by sbmalik** [comment]
@zhouyuchong **face-recognition** means identification of person face, like facenet do. face-detection is working very well. but recognition is causing trouble, if a person appears after 5,6 frames it will given a new id.

**Comment by zhouyuchong** [comment]
@sbmalik Oh, that is another problem. The **id** is from `nvtracker` and in this repo I use `NvDCF`, you can check [here](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvtracker.html) for more details.

I tried IOU, NvDCF and ReID, to be honest, none of them work very good. For your instance, if a object disappears from screen and comes back after some time, you can set `maxShadowTrackingAge`,  `probationAge` and `earlyTerminationAge` for better accuracy. 

Since the `nvtracker` is not open-source as well, there isn't a good way to solve this temporarily. So I add ArcFace to extract the facial feature. If you are building a face-recognition app, you can try to send the results out or save them locally.

**Comment by sbmalik** [comment]
@zhouyuchong sure, but how to make ArcFace works (with labels of person faces)?

**Comment by zhouyuchong** [comment]
@sbmalik the arcface works as the tertiary gie in the pipeline, and you can find the data in [here](https://github.com/zhouyuchong/face-recognition-deepstream/blob/107f3c4ead9c4757de2c61c09be1443626472cba/main.py#L164).

I didn't achieve the face comparison in the pipeline. If you want a real-time comparison, you can do it in the probe by compare the output to your own facial-feature data. Then you can add a label to the video.
